// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utuggtzkjvvlfitzeugd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dWdndHpranZ2bGZpdHpldWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjYyNDQsImV4cCI6MjA2NzY0MjI0NH0.JlGvBpTcpBPSh-TteE6o5wE5NQKBzT91w2ig3pZon8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});